spring:
  application:
    name: restaurante
  elasticsearch:
    uris: http://localhost:9210
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/restaurant-review
